### PR TITLE
Fix external link that are 'outlook protected' are opened internal.

### PR DESCRIPTION
**Pull request by micw**
This also cleans up the link config so that the JSON and the actual config are identical.

### CODE REVIEW

**Comment by fried-eggz** [comment]
Please approve this PR

**Comment by the-ryan-1** [comment]
I think there is a possibility this would also fix #256. It might also have some overlap with #265

**Comment by micw** [comment]
Yes, it should also fix #265 and probably #256 - if I know the syntax of a "verification link", I could add it to the list of default external links.

**Comment by jclsn** [comment]
Can someone please merge this? The issue is getting really annoying...

**Comment by the-ryan-1** [comment]
I checked @julian-alarcon commits and it looks like he is still somewhat active, but not nearly as active as he used to be. Could just be taking it easy for a little while. I think he linked his socials if you want to go as far as ping him on another platform. 

Otherwise, I suggest cloning micw's feature branch or merging his changes locally on your computer and running it. It's what I've been doing for awhile now and it works great.

**Comment by jclsn** [comment]
@the-ryan-1 Okay, thank you. I will see after eastern.

**Review by prov1der96 — COMMENTED** [review]
{
    "urlMainWindow":"https://outlook.live.com/mail",
    "deeplinkUrls":["outlook.com", "live.com"],
    "outlookUrls":["outlook.com", "live.com"]
    "urlsInternal":["outlook.com", "live.com"],
    "urlsExternal":["outlook.com", "live.com"]
}

**Review by prov1der96 — COMMENTED** [review]
,"deeplinkUrls":["customurl.example"]
 ,"outlookUrls":["outlookurls.example"]
 ,"externalUrls": ["externalurls.example"]

**Review by julian-alarcon — APPROVED** [review]

**Comment by micw** [comment]
Great, thank you. Are you planing a new release soon?

**Pull request merged**
